import { mkdir, writeFile } from "node:fs/promises";
import { visibleWidth } from "@earendil-works/pi-tui";
import { demoDashboard } from "../src/cli/dashboard-data.ts";
import type { ShellState } from "../src/cli/shell-commands.ts";
import { renderShell } from "../src/cli/shell-view.ts";
import { PALETTE } from "../src/cli/theme.ts";

const escape = (text: string) => text.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
const state: ShellState = { snapshot: demoDashboard(), busy: true, paused: false, offset: 0, sample: true };

async function preview(file: string, columns: number, rows: number) {
	const lines = renderShell(state, { width: columns, height: rows, color: true });
	const cell = 9.3;
	const width = Math.ceil(columns * cell + 28);
	const height = rows * 23 + 98;
	const texts: string[] = [];
	for (const [row, line] of lines.entries()) {
		let x = 14;
		let color: string = PALETTE.text;
		let weight = 400;
		// biome-ignore lint/suspicious/noControlCharactersInRegex: Parse only colors generated by the actual terminal renderer.
		for (const token of line.split(/(\x1b\[[0-9;]*m)/)) {
			if (token.startsWith("\x1b[")) {
				const parts = token.slice(2, -1).split(";").map(Number);
				if (parts[0] === 0) { color = PALETTE.text; weight = 400; }
				if (parts[0] === 1) weight = 600;
				const index = parts.indexOf(38);
				if (index >= 0 && parts[index + 1] === 2) color = `rgb(${parts.slice(index + 2, index + 5).join(",")})`;
			} else if (token) {
				texts.push(`<text x="${x.toFixed(1)}" y="${77 + row * 23}" fill="${color}" font-weight="${weight}">${escape(token)}</text>`);
				x += visibleWidth(token) * cell;
			}
		}
	}
	const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-labelledby="title desc">
<title id="title">TripleTeam interactive terminal</title><desc id="desc">The actual shell renderer displaying labeled sample data at ${columns} columns. One main view, an always available input, and a short status bar. No benchmark or performance result is shown.</desc>
<rect width="${width}" height="${height}" rx="12" fill="${PALETTE.background}"/>
<path d="M0 47H${width}" stroke="${PALETTE.border}"/>
<text x="20" y="29" font-family="system-ui,sans-serif" font-size="12" fill="${PALETTE.muted}">tripleteam demo · ${columns} columns</text>
<g font-family="DejaVu Sans Mono, Consolas, monospace" font-size="15.5" xml:space="preserve">${texts.join("\n")}</g></svg>\n`;
	await writeFile(file, svg);
}

await mkdir("docs/assets", { recursive: true });
await preview("docs/assets/terminal.svg", 100, 24);
await preview("docs/assets/terminal-narrow.svg", 48, 20);
console.log("Rendered terminal.svg and terminal-narrow.svg from the actual interactive shell.");
